import {createHmac,timingSafeEqual,scrypt as scryptCallback,randomBytes} from 'node:crypto';
import {promisify} from 'node:util';
const scrypt=promisify(scryptCallback);
export const authRequired=()=>!!(process.env.VERCEL||process.env.APP_PASSWORD_HASH);
const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&a.length===b.length&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
export function signedSession(now=Date.now()){const data=Buffer.from(JSON.stringify({exp:now+7*86400000,nonce:randomBytes(12).toString('hex')})).toString('base64url');return data+'.'+createHmac('sha256',process.env.SESSION_SECRET).update(data).digest('base64url');}
export function authorized(req,now=Date.now()){if(!authRequired())return true;if(!process.env.SESSION_SECRET)return false;try{const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('area_session='))?.slice(13);const [data,signature]=raw.split('.');if(!equal(signature,createHmac('sha256',process.env.SESSION_SECRET).update(data).digest('base64url')))return false;return JSON.parse(Buffer.from(data,'base64url')).exp>now;}catch{return false;}}
export async function passwordValid(password){if(typeof password!=='string'||password.length>256)return false;const [salt,hash]=(process.env.APP_PASSWORD_HASH||'').split(':');if(!salt||!hash)return false;const actual=(await scrypt(password,salt,32)).toString('hex');return equal(hash,actual);}
export function cookie(value,clear=false){return `area_session=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${clear?0:604800}${process.env.VERCEL?'; Secure':''}`;}
export const loginHtml=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ログイン | INCEPTION</title><style>body{margin:0;background:#f2f5f7;color:#163c57;font-family:system-ui;display:grid;min-height:100dvh;place-items:center}main{box-sizing:border-box;width:min(420px,90vw);background:white;padding:32px;border-radius:16px}small{letter-spacing:.2em}h1{font-size:24px}input,button{box-sizing:border-box;width:100%;padding:14px;font:inherit;border:1px solid #bccad3;border-radius:8px;margin:10px 0}button{background:#163c57;color:white;cursor:pointer}p{font-size:14px;line-height:1.7}</style><main><small>INCEPTION</small><h1>エリアレポート</h1><p>専用パスワードでログインしてください。</p><form action="/api/login" method="post"><label for="password">パスワード</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="256"><button>ログイン</button></form><p>__ERROR__</p></main></html>`;
