import {regionalFacilities,startFacilityUpdates,refresh,saved} from './facility-store.mjs';
import {populationRows,noAreaMessage} from './mlit-results.mjs';
import {localPlanning} from './local-planning.mjs';
import {earthquake,municipality,hazardMaps} from './public-data.mjs';
import {distance,tileFor,contains} from './geo.mjs';
import {itemById} from '../public/catalog.mjs';
const cache=new Map();
const ua='INCEPTION-AreaReport/1.0 (+https://re-inception.com/)';
async function json(url,options={}){const response=await fetch(url,{...options,headers:{'User-Agent':ua,...options.headers},signal:options.signal||AbortSignal.timeout(45000)});if(!response.ok)throw Object.assign(Error(`データ提供元の応答: HTTP ${response.status}`),{status:response.status});return response.json();}
const inFlight=new Map();
async function cached(key,fn,ttl=3600000){const hit=cache.get(key);if(hit&&hit.expires>Date.now())return hit.value;if(inFlight.has(key))return inFlight.get(key);const pending=(async()=>{try{const value=await fn();if(cache.size>300)cache.delete(cache.keys().next().value);cache.set(key,{value,expires:Date.now()+ttl});return value;}finally{inFlight.delete(key);}})();inFlight.set(key,pending);return pending;}
export async function searchAddress(query){return cached('search:'+query,async()=>{const data=await json('https://msearch.gsi.go.jp/address-search/AddressSearch?q='+encodeURIComponent(query));return data.slice(0,12).filter(x=>x.geometry?.coordinates).map(x=>({label:x.properties.title,lon:x.geometry.coordinates[0],lat:x.geometry.coordinates[1]}));});}
const filters={transit:['[railway~"^(station|halt|tram_stop)$"]','[highway=bus_stop]'],shops:['[shop~"^(supermarket|convenience)$"]'],shopping:['[shop~"^(mall|department_store)$"]'],medical:['[amenity~"^(hospital|clinic|dentist)$"]'],care:['[amenity~"^(social_facility|nursing_home)$"]'],schools:['[amenity~"^(school|kindergarten|childcare)$"]'],college:['[amenity~"^(university|college)$"]'],public:['[amenity~"^(townhall|library|police|fire_station|post_office)$"]','[leisure=park]'],other:['[amenity~"^(fuel|waste_disposal|crematorium)$"]'],spots:['[tourism~"^(attraction|museum|viewpoint)$"]']};
function matching(tags,id){switch(id){case'transit':return /^(station|halt|tram_stop)$/.test(tags.railway)||tags.highway==='bus_stop';case'shops':return /^(supermarket|convenience)$/.test(tags.shop);case'shopping':return /^(mall|department_store)$/.test(tags.shop);case'medical':return /^(hospital|clinic|dentist)$/.test(tags.amenity);case'care':return /^(social_facility|nursing_home)$/.test(tags.amenity);case'schools':return /^(school|kindergarten|childcare)$/.test(tags.amenity);case'college':return /^(university|college)$/.test(tags.amenity);case'public':return /^(townhall|library|police|fire_station|post_office)$/.test(tags.amenity)||tags.leisure==='park';case'other':return /^(fuel|waste_disposal|crematorium)$/.test(tags.amenity);case'spots':return /^(attraction|museum|viewpoint)$/.test(tags.tourism);default:return false;}}
export function startFacilitySync(){startFacilityUpdates(filters);}
async function osm(point,radius,ids){const regional=await regionalFacilities(point,radius,ids[0],filters[ids[0]]);if(regional)return regional;const query='[out:json][timeout:15];('+ids.flatMap(id=>filters[id]).map(f=>`nwr${f}(around:${radius},${point.lat},${point.lon});`).join('')+');out center tags;';return cached('osm:'+query,async()=>{for(let attempt=0;attempt<2;attempt++){try{const data=await json(process.env.OVERPASS_URL||'https://maps.mail.ru/osm/tools/overpass/api/interpreter',{method:'POST',body:new URLSearchParams({data:query}),signal:AbortSignal.timeout(25000)});if(data.remark)throw Object.assign(Error('施設データの取得が完了しませんでした。'),{status:504});if(!Array.isArray(data.elements))throw Error('施設データの形式を確認できません。');return {elements:data.elements,fetchedAt:new Date().toISOString()};}catch(e){const transient=[429,502,503,504].includes(e.status)||e.name==='TimeoutError'||e.name==='AbortError'||e.message==='fetch failed';if(attempt===0&&transient){await new Promise(resolve=>setTimeout(resolve,1500));continue;}throw Error(transient?'施設データ提供元が混雑しているか、通信がタイムアウトしました。自動再試行でも取得できませんでした。時間をおいて再作成してください。':e.message);}}});}
async function mlit(endpoint,point){if(!process.env.REINFOLIB_API_KEY)return null;const tile=tileFor(point.lat,point.lon);return cached(endpoint+JSON.stringify(tile),()=>json('https://www.reinfolib.mlit.go.jp/ex-api/external/'+endpoint+'?'+new URLSearchParams({response_format:'geojson',...tile}),{headers:{'Ocp-Apim-Subscription-Key':process.env.REINFOLIB_API_KEY}}),86400000);}
const mlitSource='国土交通省 不動産情報ライブラリ';
export async function collect({point,radius,selected}){
 const results={};const osmIds=selected.filter(id=>itemById[id].provider==='osm');
 const missing=id=>({id,status:'unavailable',rows:[],message:'自動取得の接続先が未設定です。確認済み資料を「調査メモ」から追加できます。',source:'未取得'});
 const tasks=[];
 if(osmIds.length)tasks.push((async()=>{const queue=[...osmIds];async function worker(){while(queue.length){const id=queue.shift();try{const {elements,fetchedAt,storageNote}=await osm(point,radius,[id]);const rows=elements.filter(x=>matching(x.tags||{},id)).map(x=>{const lat=x.lat??x.center?.lat,lon=x.lon??x.center?.lon;return {name:x.tags['name:ja']||x.tags.name||'名称未登録',lat,lon,distance:Math.round(distance(point,{lat,lon})),osmId:x.type+'/'+x.id};}).filter(x=>Number.isFinite(x.distance)&&x.distance<=radius).sort((a,b)=>a.distance-b.distance);results[id]={id,status:'ok',rows,message:(storageNote?storageNote+' ':'')+(rows.length?'距離は地点からの直線距離です。徒歩経路・所要時間ではありません。':'公開データで該当施設が見つかりませんでした。施設が存在しないことを示すものではありません。'),source:'© OpenStreetMap contributors (ODbL)',sourceUrl:'https://www.openstreetmap.org/copyright',scope:`半径${radius}m・地図登録施設`,fetchedAt};}catch(e){results[id]={...missing(id),status:'error',message:e.message,source:'OpenStreetMap / Overpass API'};}}}await Promise.all(Array.from({length:Math.min(2,queue.length)},()=>worker()));})());
 for(const id of selected.filter(id=>!osmIds.includes(id))){tasks.push((async()=>{const def=itemById[id];results[id]=missing(id);try{
 if(def.provider==='local-planning'){results[id]={id,...await localPlanning(point,id)};}
 else if(def.provider==='jshis'){results[id]={id,...await earthquake(point)};}
 else if(def.provider==='dashboard'){results[id]={id,...await municipality(point,id)};}
 else if(def.provider==='hazard'){results[id]={id,...await hazardMaps(point,radius,id)};}
 else if(def.provider==='gsi'){const d=await cached('elevation:'+JSON.stringify(point),()=>json(`https://cyberjapandata2.gsi.go.jp/general/dem/scripts/getelevation.php?lat=${point.lat}&lon=${point.lon}&outtype=JSON`));if(typeof d.elevation!=='number')throw Error('この地点の標高データを取得できません。');results[id]={id,status:'ok',rows:[{name:'標高',value:d.elevation+' m'},{name:'標高データの種類',value:d.hsrc}],source:'国土地理院 標高API',sourceUrl:'https://maps.gsi.go.jp/development/elevation_s.html',scope:'選択地点（標高モデルによる値）',message:'実測値ではありません。',fetchedAt:new Date().toISOString()};}
 else if(def.provider==='map'){results[id]={id,status:'ok',rows:[],source:'国土地理院 シームレス空中写真',sourceUrl:'https://maps.gsi.go.jp/development/ichiran.html',scope:'選択地点周辺',message:'撮影時期は地域により異なります。最新の現況を保証するものではありません。',mapLayer:'seamlessphoto',fetchedAt:new Date().toISOString()};}
 else if(def.provider.startsWith('mlit:')){const endpoint=def.provider.split(':')[1];const d=await mlit(endpoint,point);if(!d){results[id].message='国土交通省APIの接続設定が必要です。現在はデータ未取得です。';return;}if(Array.isArray(d)&&d.length===0)d.features=[];if(!Array.isArray(d.features))throw Error('取得した地理データの形式を確認できません。');const features=d.features.filter(f=>contains(f.geometry,[point.lon,point.lat]));let rows=[];
 if(id==='zoning')rows=features.flatMap(f=>[['用途地域',f.properties.use_area_ja],['建ぺい率',f.properties.u_building_coverage_ratio_ja],['容積率',f.properties.u_floor_area_ratio_ja],['告示日',f.properties.decision_date]].filter(x=>x[1]!=null&&x[1]!=='').map(([name,value])=>({name,value})));
 else if(id==='flood')rows=features.map(f=>({name:f.properties.A31a_202||'河川名未収録',value:'浸水深ランク '+f.properties.A31a_205+'（原典の凡例で確認）'}));
 else if(id==='division')rows=features.map(f=>({name:'区域区分',value:f.properties.area_classification_ja||'未収録',note:'告示日 '+(f.properties.decision_date||'未収録')}));
 else if(id==='tsunami')rows=features.map(f=>({name:'津波浸水深',value:f.properties.A40_003||'未収録',note:'対象年 '+(f.properties.target_year||'未収録')}));
 else if(id==='landslide')rows=features.flatMap(f=>[{name:'区域名',value:f.properties.A33_005||'未収録'},{name:'現象の種類コード',value:f.properties.A33_001},{name:'区域区分コード',value:f.properties.A33_002},{name:'公示日',value:f.properties.A33_007||'未収録'}]);
 else if(id==='population')rows=populationRows(features);
 else rows=features.flatMap(f=>Object.entries(f.properties).filter(([k,v])=>/^PT00_\d{4}$/.test(k)&&Number.isFinite(Number(v))&&Number(v)>=0).map(([k,v])=>({name:k.slice(-4)+'年 人口',value:Math.round(Number(v)*10)/10+' 人',note:'250mメッシュ '+f.properties.MESH_ID}))).sort((a,b)=>a.name.localeCompare(b.name));
 results[id]={id,status:rows.length?'ok':'unavailable',rows,source:mlitSource,sourceUrl:'https://www.reinfolib.mlit.go.jp/help/apiManual/'+endpoint.toLowerCase()+'/',scope:(id==='population'||id==='future')?'地点を含む250mメッシュ（半径内の人口ではありません）':'選択地点を含む区域',geometries:features.map(f=>f.geometry),message:rows.length?'提供元の調査年・区域境界を確認してください。区域コードは原典の凡例を参照してください。':(['landslide','tsunami','flood'].includes(id)?noAreaMessage(d.features.length):'この地点の必要な人口項目を確認できません。'),querySucceeded:true,matchedAreas:features.length,tileAreas:d.features.length,fetchedAt:new Date().toISOString()};}
 }catch(e){results[id]={...missing(id),status:'error',message:e.message};}})());}
 await Promise.all(tasks);return {point,radius,selected,results,generatedAt:new Date().toISOString()};
}

export async function refreshFacilitiesCloud(){const queue=Object.entries(filters),results={};async function worker(){while(queue.length){const [id,values]=queue.shift();try{const previous=await saved(id);if(previous&&Date.now()-Date.parse(previous.fetchedAt)<23*3600000){results[id]='fresh';continue;}const data=await refresh(id,values);results[id]=data.elements.length;}catch{results[id]='retry-next-run';}}}await Promise.all([worker(),worker(),worker()]);return results;}
