import {cloudEnabled,readCloud,writeCloud} from './cloud-store.mjs';
import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve,sep} from 'node:path';
const folder=process.env.FACILITY_CACHE_DIR?pathToFileURL(resolve(process.env.FACILITY_CACHE_DIR)+sep):new URL('../data/facilities/',import.meta.url);
const bounds=[34.78,135.70,35.00,135.97];
const day=86400000;
const running=new Map(),lastAttempt=new Map();
export function covers(point,radius){const dy=radius/110000,dx=radius/(110000*Math.cos(point.lat*Math.PI/180));return point.lat-dy>=bounds[0]&&point.lon-dx>=bounds[1]&&point.lat+dy<=bounds[2]&&point.lon+dx<=bounds[3];}
export async function saved(id){try{const d=(cloudEnabled()?await readCloud('facilities/'+id+'.json'):JSON.parse(await readFile(new URL(id+'.json',folder),'utf8')));return d?.version===1&&Array.isArray(d.elements)&&Number.isFinite(Date.parse(d.fetchedAt))?d:null;}catch{return null;}}
export function refresh(id,filters){if(running.has(id))return running.get(id);const pending=(async()=>{lastAttempt.set(id,Date.now());const exact=filters.flatMap(f=>{const m=f.match(/^\[(\w+)~"\^\(([^)]+)\)\$"\]$/);return m?m[2].split('|').map(v=>'['+m[1]+'='+v+']'):[f];});const query='[out:json][timeout:45];('+exact.map(f=>`nwr${f}(${bounds.join(',')});`).join('')+');out center tags;';const r=await fetch(process.env.OVERPASS_URL||'https://maps.mail.ru/osm/tools/overpass/api/interpreter',{method:'POST',body:new URLSearchParams({data:query}),signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('施設更新 HTTP '+r.status);const d=await r.json();if(d.remark||!Array.isArray(d.elements))throw Error('施設データの取得が不完全です');const value={version:1,bounds,elements:d.elements,fetchedAt:new Date().toISOString()};if(cloudEnabled()){await writeCloud('facilities/'+id+'.json',value);return value;}await mkdir(folder,{recursive:true});await writeFile(new URL(id+'.tmp',folder),JSON.stringify(value));await rename(new URL(id+'.tmp',folder),new URL(id+'.json',folder));return value;})().finally(()=>running.delete(id));running.set(id,pending);return pending;}
export async function regionalFacilities(point,radius,id,filters){if(process.env.FACILITY_STORE_DISABLED==='1'||!covers(point,radius))return null;const old=await saved(id);if(old){const stale=Date.now()-Date.parse(old.fetchedAt)>day;if(!process.env.VERCEL&&stale&&Date.now()-(lastAttempt.get(id)||0)>3600000)refresh(id,filters).catch(()=>{});return {...old,storageNote:stale?'保存済みデータを使用（24時間以上経過）。更新は未完了です。':'保存済みの地域データを使用。'};}if(Date.now()-(lastAttempt.get(id)||0)<3600000&&!running.has(id))return null;try{return {...await refresh(id,filters),storageNote:'地域データを取得・保存しました。'};}catch{return null;}}
export function startFacilityUpdates(filters){let active=false;const update=async()=>{if(active)return;active=true;try{for(const [id,values]of Object.entries(filters)){const old=await saved(id);if(old&&Date.now()-Date.parse(old.fetchedAt)<day)continue;if(Date.now()-(lastAttempt.get(id)||0)<3600000)continue;try{await refresh(id,values);console.log('施設データ更新: '+id);}catch{console.warn('施設データ更新延期: '+id);}await new Promise(r=>setTimeout(r,1500));}}finally{active=false;}};update();const timer=setInterval(update,3600000);timer.unref();}
